export const SIMULATION_NAMES = [
  "Venu Madhav Sharma",
  "Mahadev Chowdary",
  "Pandu Babu",
  "Sudarshan Rao",
  "Rajkumar Naidu",
  "Prabhu Naidu",
  "Siva Nageswara Rao",
  "Nikhil Chowdary",
  "Manohar Goud",
  "Raghavendra Setty",
  "Vinod Naidu",
  "Murali Reddy",
  "Raghunath Babu",
  "Balakrishna Chowdary",
  "Sai Srikar Naidu",
  "Naga Malleswara Rao",
  "Satyam",
  "Kishore",
  "Yugandhar Goud",
  "Harinath",
  "Rahul Chowdary",
  "Sujith Yadav",
  "Gopal Babu",
  "Pradyumna",
  "Ramana Goud",
  "Shekar Goud",
  "Madhava",
  "Yadagiri Yadav",
  "Narendra",
  "Balachandra",
  "Venu Madhav",
  "Muni Ratnam",
  "Rahul",
  "Chinna",
  "Goutham",
  "Nagesh Chowdary",
  "Vasanth Reddy",
  "Durga Prasad Setty",
  "Hanumanth Reddy",
  "Hari Krishna Goud",
  "Abhi",
  "Uday Naidu",
  "Parthasarathy Chowdary",
  "Manikanta",
  "Sudhir",
  "Venkataramaiah Sharma",
  "Srivastav",
  "Vijaya Kumar Varma",
  "Shashank Babu",
  "Vishnu Vardhan Babu",
  "Upendra",
  "Deva Babu",
  "Kasi Viswanath Rao",
  "Prasad Sharma",
  "Siddharth Goud",
  "Vasanth",
  "Yerra Swamy Goud",
  "Raja Chowdary",
  "Prem",
  "Sudhir Babu",
  "Indrasena",
  "Aravind",
  "Sandeep",
  "Prabhakar Goud",
  "Om Prakash Rao",
  "Suryaprakash Varma",
  "Madhusudhan Goud",
  "Mahendra Varma",
  "Siva Prasad Babu",
  "Chidananda",
  "Dinesh",
  "Rajendra",
  "Pratap Yadav",
  "Deepak Sharma",
  "Venu Gopal Sharma",
  "Lokanath Sharma",
  "Guru Prasad Chowdary",
  "Nagendra Babu",
  "Aditya Naidu",
  "Guru",
  "Manoj Setty",
  "Mahesh Babu",
  "Dileep",
  "Dhruv Babu",
  "Satyanarayana Reddy",
  "Meherbaba Naidu",
  "Vijay Rao",
  "Vinay Goud",
  "Ramaiah Babu",
  "Deva",
  "Seetharam Naidu",
  "Akash Naidu",
  "Harsha Vardhan Naidu",
  "Naga Raju",
  "Nagarjuna Reddy",
  "Akhil Setty",
  "Chandrakanth",
  "Keerthan Sharma",
  "Muni Ratnam Setty",
  "Sudhir Sharma",
  "Pradyumna Reddy",
  "Ramaraju Babu",
  "Kumar Swamy",
  "Surendra",
  "Krishna Mohan Yadav",
  "Sampath Chowdary",
  "Manoj Kumar",
  "Yugandhar",
  "Pratap Babu",
  "Charan Varma",
  "Adarsh",
  "Vijay Chowdary",
  "Bhanu Sharma",
  "Rajesh",
  "Varaprasad Chowdary",
  "Rajanna Rao",
  "Hanumanth",
  "Rajkumar",
  "Siva Prasad Varma",
  "Kiran Setty",
  "Siva Babu",
  "Satyanarayana",
  "Yogesh",
  "Sarath Chandra",
  "Akhil Rao",
  "Balaji",
  "Indra Naidu",
  "Ashwin Babu",
  "Seshu Goud",
  "Sai Krishna Goud",
  "Nagendra Naidu",
  "Chittibabu Setty",
  "Suryakiran Setty",
  "Amar Goud",
  "Shyam Goud",
  "Swaroop",
  "Venu Madhav Rao",
  "Vasu Naidu",
  "Bhaskar Yadav",
  "Sudheer Rao",
  "Rathnam Chowdary",
  "Abhishek Sharma",
  "Vikram Yadav",
  "Hemanth Kumar Babu",
  "Rohit",
  "Gautam Chowdary",
  "Srivastav Naidu",
  "Raja Sekhar Reddy",
  "Balachandra Chowdary",
  "Purushotham",
  "Ishwar Rao",
  "Krishna Naidu",
  "Nagabhushan Goud",
  "Laxman",
  "Dhanush",
  "Manoj Kumar Sharma",
  "Ramaraju Varma",
  "Madhu Yadav",
  "Kalyan Setty",
  "Guru Babu",
  "Pavan Sharma",
  "Raghavendra Yadav",
  "Satyam Chowdary",
  "Rajendra Sharma",
  "Murali Krishna Naidu",
  "Purushotham Goud",
  "Nagendra",
  "Rajesh Varma",
  "Rishi",
  "Rishi Yadav",
  "Prabhu",
  "Subhash",
  "Tarun Goud",
  "Sai Krishna Rao",
  "Gangadhar Chowdary",
  "Sai Vamsi",
  "Trinath Yadav",
  "Manoj Kumar Goud",
  "Mohan",
  "Rajesh Setty",
  "Lakshman Babu",
  "Mohan Krishna Goud",
  "Raja Sekhar Setty",
  "Jai Naidu",
  "Suresh Naidu",
  "Daya Sagar Reddy",
  "Satya Prakash",
  "Pradeep Babu",
  "Manikanta Rao",
  "Kamalakar Goud",
  "Anand Chowdary",
  "Jashwanth",
  "Chidananda Setty",
  "Devendra",
  "Shiva Kumar Naidu",
  "Sarath Setty",
  "Ganesh Goud",
  "Venkata Ramana Reddy",
  "Satya Prakash Naidu",
  "Sai Teja",
  "Naresh Reddy",
  "Teja Goud",
  "Keerthan Yadav",
  "Vikas Naidu",
  "Ranvir Chowdary",
  "Teja Varma",
  "Varun",
  "Sanjay",
  "Ajay",
  "Devendra Setty",
  "Durga Rao",
  "Rithvik Babu",
  "Ramu Babu",
  "Venkata Krishna Babu",
  "Sai Charan",
  "Sarath Chandra Chowdary",
  "Ravi",
  "Vikram",
  "Shiva Charan Naidu",
  "Eshwar Naidu",
  "Anil Goud",
  "Vikas Varma",
  "Amar Sharma",
  "Chandu Babu",
  "Marthand",
  "Lokesh",
  "Suryaprakash",
  "Jayanth Babu",
  "Raghavendra",
  "Subba Rao",
  "Bhargav",
  "Chiru Reddy",
  "Trinadha Rao",
  "Marthand Sharma",
  "Charan Chowdary",
  "Sagar",
  "Naresh",
  "Varun Babu",
  "Purnachandra Rao",
  "Siddharth Chowdary",
  "Ganapathi Varma",
  "Shanmukha Rao",
  "Shashank",
  "Peddi Raju Setty",
  "Harsha Goud",
  "Vamsi Babu",
  "Nagesh Naidu",
  "Venkataramaiah Babu",
  "Trivikram Chowdary",
  "Kranthi Chowdary",
  "Hemanth Kumar",
  "Manohar Setty",
  "Amarnath Sharma",
  "Vijaya Simha Setty",
  "Abhishek Naidu",
  "Satyanand Reddy",
  "Abhishek",
  "Sai",
  "Ashok Varma",
  "Hari Babu",
  "Chandrahas Setty",
  "Vishnu Rao",
  "Ramakanth Varma",
  "Suresh",
  "Varaprasad",
  "Prashanth",
  "Venkatesh Reddy",
  "Girindra Chowdary",
  "Adarsh Rao",
  "Ajith",
  "Ramanjaneyulu Varma",
  "Pratap",
  "Nanda Kishore Babu",
  "Suryanarayana Yadav",
  "Raman Goud",
  "Dhanush Reddy",
  "Prabhu Das",
  "Kalyan Chakravarthy Setty",
  "Deva Reddy",
  "Nagarjuna",
  "Pulla Rao",
  "Suneel",
  "Gautam Naidu",
  "Indra Goud",
  "Chandrahas",
  "Rohit Babu",
  "Satya Prakash Setty",
  "Ramesh",
  "Anil",
  "Gopi",
  "Ravi Teja",
  "Shashi Kiran",
  "Murali Naidu",
  "Shiva Charan Goud",
  "Sai Charan Reddy",
  "Rambabu",
  "Pruthvi",
  "Satyanand Naidu",
  "Srikanth Goud",
  "Kasi Viswanath",
  "Rohit Setty",
  "Gowri Shankar Rao",
  "Madhusudhan Chowdary",
  "Santosh Reddy",
  "Ashwin Kumar Reddy",
  "Meher Varma",
  "Hemanth Reddy",
  "Vidyadhar Varma",
  "Pavan",
  "Hanumantha Rao",
  "Tataji",
  "Vamsidhar Chowdary",
  "Ramanjaneyulu Sharma",
  "Naveen Setty",
  "Mukesh",
  "Srikanth Babu",
  "Gunashekar",
  "Siva Sankar",
  "Bala",
  "Ravi Kiran",
  "Raghava Goud",
  "Chinni Krishna Babu",
  "Gopi Varma",
  "Kesava Naidu",
  "Ravi Shankar",
  "Jaya Prakash",
  "Hemanth Sharma",
  "Srikar Rao",
  "Chaitanya",
  "Krishna Chaitanya Rao",
  "Satyam Rao",
  "Santosh",
  "Ramakrishna Reddy",
  "Kamalakar Rao",
  "Mahesh",
  "Chandra Sekhar",
  "Chiru",
  "Naga Raju Rao",
  "Sreekanth Sharma",
  "Kumar Swamy Yadav",
  "Meher Naidu",
  "Ratna Kumar",
  "Amarnath Goud",
  "Hanumanth Chowdary",
  "Vardhan Yadav",
  "Peddi Raju",
  "Rithesh Yadav",
  "Pruthvi Sharma",
  "Praneeth Babu",
  "Kalyan Chakravarthy",
  "Srinivas",
  "Phani Naidu",
  "Ramakanth",
  "Varun Yadav",
  "Nookaraju Babu",
  "Ashwin Kumar Goud",
  "Hrushikesh Setty",
  "Balakrishna Varma",
  "Sai Ganesh",
  "Narsimha",
  "Rithvik",
  "Chandrahas Chowdary",
  "Shiva",
  "Pradeep Chowdary",
  "Suresh Babu",
  "Raghunath",
  "Sujith Chowdary",
  "Siva Sankar Chowdary",
  "Krishna",
  "Goutham Yadav",
  "Sreenath",
  "Sunil Yadav",
  "Sudheer Sharma",
  "Chinni Krishna Naidu",
  "Pandurangaiah Setty",
  "Jeevan",
  "Tataji Yadav",
  "Praveen Kumar Yadav",
  "Shankar Naidu",
  "Girish Goud",
  "Sai Ram",
  "Rambabu Sharma",
  "Chetan",
  "Chandrakanth Reddy",
  "Keerthan",
  "Srihari",
  "Haranath",
  "Avinash Sharma",
  "Sandeep Reddy",
  "Chidananda Varma",
  "Balaraju Babu",
  "Aditya Reddy",
  "Tataji Rao",
  "Parasuram",
  "Thirupathi Yadav",
  "Kanaka Raju Sharma",
  "Balaraju",
  "Lokanath",
  "Hemachandra",
  "Vijaya Kumar",
  "Vidyadhar",
  "Venkat Babu",
  "Uday Kiran Babu",
  "Umapathi Setty",
  "Ganesh Setty",
  "Shashank Goud",
  "Chandu",
  "Murali Mohan",
  "Subhash Goud",
  "Venkata Ramana",
  "Sagar Chowdary",
  "Nagabhushan",
  "Gopi Rao",
  "Pandurangaiah Babu",
  "Jai",
  "Ramakanth Goud",
  "Ramakrishna",
  "Girish",
  "Satya Yadav",
  "Hari Charan Setty",
  "Seshu Babu",
  "Raghu",
  "Kanaka Raju",
  "Karthik Varma",
  "Pattabhi Setty",
  "Mahendra",
  "Sampath Goud",
  "Rudra Reddy",
  "Bujji Naidu",
  "Venu",
  "Bhargav Varma",
  "Ravi Kiran Sharma",
  "Shiva Sai",
  "Meherbaba",
  "Haranath Goud",
  "Ashok",
  "Venkataramaiah",
  "Jayaram Babu",
  "Ishwar Goud",
  "Sai Praneeth Rao",
  "Kiran Chowdary",
  "Vamsi Krishna Rao",
  "Naga Raju Goud",
  "Pavan Goud",
  "Sai Kiran Chowdary",
  "Krishna Yadav",
  "Madhusudhan",
  "Upendra Reddy",
  "Pavan Kalyan Goud",
  "Rudra Naidu",
  "Nithish Babu",
  "Shivaji Setty",
  "Nithin",
  "Jagan",
  "Thirupathi",
  "Shiva Kumar",
  "Dileep Yadav",
  "Pranav",
  "Gangadhar",
  "Mohan Krishna Setty",
  "Sampath",
  "Nikhil Sharma",
  "Narayana Yadav",
  "Avinash",
  "Nanda Kishore",
  "Sreeram Yadav",
  "Koteswara Rao",
  "Jayanth",
  "Veerabhadra Yadav",
  "Raman Rao",
  "Ranvir",
  "Bharath Naidu",
  "Kaushik Naidu",
  "Bala Varma",
  "Nagabhushan Babu",
  "Subbu",
  "Hemanth Kumar Goud",
  "Karthik Goud",
  "Mahadev",
  "Gautam",
  "Yaswanth Chowdary",
  "Sai Teja Yadav",
  "Yaswanth",
  "Shankar Rao",
  "Vidyadhar Goud",
  "Vidyasagar",
  "Srinu Rao",
  "Gopal",
  "Bhanu Reddy",
  "Gopal Chowdary",
  "Raja Sekhar",
  "Nookaraju Goud",
  "Adarsh Naidu",
  "Srinu Chowdary",
  "Upendra Setty",
  "Suryakiran Naidu",
  "Shiva Krishna Chowdary",
  "Hemachandra Chowdary",
  "Srivastav Yadav",
  "Rakesh",
  "Manoj",
  "Vidyasagar Varma",
  "Vinay",
  "Dhanunjay",
  "Sai Babu",
  "Jagadeesh Varma",
  "Rajanna",
  "Prakash Varma",
  "Peddi Raju Yadav",
  "Vamsi",
  "Chittibabu Goud",
  "Sudheer Babu",
  "Balaraju Yadav",
  "Ranvir Setty",
  "Hemanth",
  "Kalyan Chakravarthy Sharma",
  "Haranath Chowdary",
  "Umesh Naidu",
  "Prashanth Reddy",
  "Parthasarathy Varma",
  "Manoj Varma",
  "Kanakaiah Yadav",
  "Suhas Sharma",
  "Suryanarayana",
  "Mahesh Naidu",
  "Ashok Rao",
  "Ramaiah",
  "Uday Reddy",
  "Raghuram Reddy",
  "Ravindra Rao",
  "Shiva Prasad Babu",
  "Sai Srikar",
  "Mallikarjun Sharma",
  "Kanakaiah Reddy",
  "Prasanna Kumar Rao",
  "Malli Chowdary",
  "Sai Ram Rao",
  "Krishna Mohan",
  "Malli",
  "Girish Yadav",
  "Kaushik Setty",
  "Pruthvi Rao",
  "Ashwin Setty",
  "Pramod Setty",
  "Lokanath Rao",
  "Shashi Kiran Varma",
  "Meherbaba Chowdary",
  "Ajay Yadav",
  "Vishal Setty",
  "Veerendra Varma",
  "Vishnu Vardhan Rao",
  "Venu Varma",
  "Shiva Charan",
  "Rajkumar Yadav",
  "Jayanth Sharma",
  "Pandu",
  "Vishnu",
  "Suryaprakash Sharma",
  "Narsimha Goud",
  "Srinivas Sharma",
  "Krishna Chaitanya Setty",
  "Dhanush Setty",
  "Praveen Kumar Sharma",
  "Madhava Sharma",
  "Veerraju Sharma",
  "Dhanunjay Varma",
  "Sarath Chandra Sharma",
  "Indrasena Goud",
  "Ashwin Kumar",
  "Pradeep",
  "Srikanth",
  "Bhargav Yadav",
  "Rambabu Babu",
  "Satya",
  "Vijaya Kumar Chowdary",
  "Sunil Setty",
  "Jaggu Setty",
  "Prasanna Kumar Babu",
  "Laxman Babu",
  "Subrahmanyam Varma",
  "Hanuman Yadav",
  "Ramana",
  "Sasi",
  "Shiva Krishna",
  "Phani",
  "Viswanath Yadav",
  "Ravi Shankar Varma",
  "Phani Setty",
  "Venu Gopal",
  "Raghu Sharma",
  "Kamalakar",
  "Swamy Babu",
  "Balachandra Naidu",
  "Sumanth Yadav",
  "Prasad Goud",
  "Sai Naidu",
  "Naveen",
  "Shiva Prasad Yadav",
  "Pavan Kalyan Babu",
  "Trivikram Sharma",
  "Hasini Kumari",
  "Kalavathi Bai",
  "Tulasi",
  "Sunitha Sri",
  "Srujana Reddy",
  "Keerthana",
  "Madhavi Naidu",
  "Keerthi",
  "Nagalakshmi Priya",
  "Radha Priya",
  "Vanaja Naidu",
  "Suryakala",
  "Manisha Naidu",
  "Chandana",
  "Shailaja Bai",
  "Jayasri",
  "Pavani",
  "Pallavi Priya",
  "Santoshi Devi",
  "Jyothsna Bai",
  "Sai Ramya Sri",
  "Rachana Kumari",
  "Jaya Bai",
  "Jhansi",
  "Bhargavi",
  "Hema",
  "Padma Bai",
  "Santhi Kumari",
  "Trisha",
  "Pranitha",
  "Ashwini Latha",
  "Varsha",
  "Malliswari Kumari",
  "Sumalatha",
  "Vinitha",
  "Radhika Sri",
  "Lasya Kumari",
  "Sreelatha Reddy",
  "Vasundhara Naidu",
  "Veena",
  "Kalindi Rani",
  "Madhuri Reddy",
  "Santhi Priya",
  "Vishnu Priya",
  "Kusuma",
  "Gowri Reddy",
  "Sujitha Latha",
  "Geetha",
  "Anu",
  "Snigdha",
  "Swarna",
  "Alekhya",
  "Sharada Naidu",
  "Sruthi Kumari",
  "Vanaja",
  "Charitha Reddy",
  "Sravani Reddy",
  "Pooja Naidu",
  "Indraja",
  "Prasanna",
  "Sathya Sri",
  "Malliswari Priya",
  "Bhavani Naidu",
  "Rekha Bai",
  "Anusha Bai",
  "Vaishnavi Reddy",
  "Poojitha",
  "Keerthana Naidu",
  "Harini Priya",
  "Bhavani Rani",
  "Chinnari Rani",
  "Shanthi Latha",
  "Amulya Reddy",
  "Pravallika Sri",
  "Sulochana Latha",
  "Bhargavi Latha",
  "Sandhya",
  "Asha Devi",
  "Kausalya Sri",
  "Naga Jyothi",
  "Sameera Reddy",
  "Indu Reddy",
  "Sarayu Bai",
  "Mounika Naidu",
  "Aparna",
  "Sarada",
  "Sai Priya",
  "Susmitha",
  "Sindhu Priya",
  "Srujana",
  "Kausalya",
  "Madhuri",
  "Siri",
  "Nikhita Latha",
  "Leela Latha",
  "Priyanka",
  "Sanjeevani Devi",
  "Varsha Latha",
  "Sarada Priya",
  "Poojitha Priya",
  "Kavitha Sri",
  "Sneha",
  "Suguna Latha",
  "Padmini Priya",
  "Veda",
  "Varshini Rani",
  "Padmavathi",
  "Ramya Latha",
  "Sreelatha Priya",
  "Rajani Kanth Reddy",
  "Kalpana",
  "Anjali",
  "Mahalakshmi Rani",
  "Anusha",
  "Mythri",
  "Sanjana Rani",
  "Srilekha",
  "Pranitha Sri",
  "Vidya Sri",
  "Sahithi Bai",
  "Varalakshmi Naidu",
  "Satya Vathi Reddy",
  "Pranathi",
  "Durga",
  "Bhoomika Sri",
  "Meghana",
  "Ramadevi Sri",
  "Pranathi Naidu",
  "Shalini",
  "Manisha Latha",
  "Girija",
  "Sindhu",
  "Sita",
  "Sreekala",
  "Suguna Kumari",
  "Shobha",
  "Lalitha Naidu",
  "Suryakala Bai",
  "Bhavya",
  "Jyostna Naidu",
  "Geetha Latha",
  "Krupa Sri",
  "Sruthi Sri",
  "Rajitha Bai",
  "Renuka Rani",
  "Vasanthi",
  "Sulochana",
  "Sirisha Bai",
  "Rajani Sri",
  "Kavitha",
  "Ramadevi Priya",
  "Meenakshi",
  "Sai Ramya Kumari",
  "Sujatha Sri",
  "Nandini Rani",
  "Sowmya Latha",
  "Pooja Kumari",
  "Sahasra Kumari",
  "Madhulika",
  "Srilatha Bai",
  "Indira",
  "Aparajitha Naidu",
  "Satya Vathi Kumari",
  "Sita Kumari",
  "Satya Vathi",
  "Manvitha",
  "Alekhya Kumari",
  "Girija Latha",
  "Sarala Devi",
  "Charitha",
  "Parvathi Devi",
  "Rekha",
  "Ragini",
  "Varshini Naidu",
  "Vaidehi Sri",
  "Santoshi Priya",
  "Manisha",
  "Vimala",
  "Sasikala Devi",
  "Vaishnavi Bai",
  "Priyanka Sri",
  "Sai Sri",
  "Indu",
  "Santoshi",
  "Supriya Naidu",
  "Spandana",
  "Roja",
  "Lakshana",
  "Sriya Priya",
  "Rukmini",
  "Shirisha",
  "Pooja",
  "Vaani",
  "Ramanamma Devi",
  "Trisha Naidu",
  "Geetha Rani",
  "Durga Kumari",
  "Susmitha Naidu",
  "Sitara Devi",
  "Tanvi",
  "Vasundhara Devi",
  "Srilatha Rani",
  "Indraja Reddy",
  "Nirmala",
  "Santhi",
  "Chandrika",
  "Varsha Naidu",
  "Anjali Reddy",
  "Manjula Kumari",
  "Sirisha",
  "Tanvi Kumari",
  "Pavani Bai",
  "Shobha Naidu",
  "Preethi Priya",
  "Shalini Priya",
  "Sowbhagya Sri",
  "Varshini",
  "Poornima Priya",
  "Madhulika Sri",
  "Kavya",
  "Saroja Rani",
  "Sumalatha Reddy",
  "Leela",
  "Nayana",
  "Sharada Kumari",
  "Vasanthi Priya",
  "Bindu Kumari",
  "Sanjeevani Reddy",
  "Padmaja",
  "Bhagya Lakshmi Bai",
  "Deepthi",
  "Shanthi",
  "Shruti",
  "Lahari Naidu",
  "Vidya Reddy",
  "Manasa Kumari",
  "Poornima Devi",
  "Ragini Sri",
  "Sasikala",
  "Aparna Priya",
  "Vijaya Lakshmi Sri",
  "Deepika Reddy",
  "Usha",
  "Sangeetha",
  "Sowjanya Naidu",
  "Nalini Latha",
  "Gowri",
  "Shyamala Rani",
  "Sangeetha Rani",
  "Vimala Sri",
  "Usha Rani",
  "Jayasri Sri",
  "Sowjanya",
  "Kiranmayi Kumari",
  "Tanvi Rani",
  "Pallavi",
  "Tejaswini Latha",
  "Divya Priya",
  "Bhoomika",
  "Devika",
  "Sravani Priya",
  "Sruthi",
  "Srilekha Rani",
  "Sreepriya Naidu",
  "Spandana Sri",
  "Deepti",
  "Saraswathi Devi",
  "Mamatha Rani",
  "Suryakala Naidu",
  "Savitri Devi",
  "Chinnari Sri",
  "Lasya Devi",
  "Kiranmayi",
  "Sujitha",
  "Krishnaveni Rani",
  "Madhavi",
  "Padmini Bai",
  "Sasi Rekha",
  "Amulya",
  "Swathi Devi",
  "Lakshana Sri",
  "Sridevi",
  "Sailaja Bai",
  "Veena Devi",
  "Uma",
  "Aruna",
  "Jahnavi",
  "Aruna Reddy",
  "Lahari",
  "Deepika Devi",
  "Pranathi Rani",
  "Sriya Latha",
  "Tulasi Bai",
  "Haritha",
  "Manasa Sri",
  "Shanti Priya",
  "Suhasini Kumari",
  "Revathi Sri",
  "Sai Lakshmi",
  "Jyostna Bai",
  "Padmini",
  "Sanjana Sri",
  "Gayatri Naidu",
  "Manjula Priya",
  "Padmavathi Reddy",
  "Lakshana Bai",
  "Lavanya Devi",
  "Lalitha",
  "Mounika Devi",
  "Pravallika",
  "Saraswathi Sri",
  "Shyamala",
  "Mythri Reddy",
  "Bindu",
  "Suchitra Rani",
  "Meenakshi Priya",
  "Shravya Priya",
  "Sahasra Kiran",
  "Kalyani Rani",
  "Sneha Kumari",
  "Shreya Bai",
  "Snigdha Naidu",
  "Kamala Priya",
  "Lakshmi Devi",
  "Anu Devi",
  "Sasi Rekha Naidu",
  "Deepika",
  "Ishika",
  "Keerthi Latha",
  "Yasoda Latha",
  "Kalyani",
  "Indira Naidu",
  "Kalyani Naidu",
  "Sarala Bai",
  "Lavanya",
  "Sahiti",
  "Pavani Rani",
  "Harshitha Naidu",
  "Harini",
  "Padma Priya",
  "Nireeksha Reddy",
  "Neha Rani",
  "Sasi Rekha Rani",
  "Nishitha Sri",
  "Malliswari",
  "Girija Naidu",
  "Mokshitha Naidu",
  "Jhansi Latha",
  "Latha",
  "Dhanya Devi",
  "Naga Mani Reddy",
  "Suhasini Latha",
  "Jyothi Bai",
  "Sailaja Reddy",
  "Gnaneswari Rani",
  "Pallavi Reddy",
  "Tanuja Rani",
  "Sumalatha Rani",
  "Sai Lakshmi Bai",
  "Naga Mani",
  "Sunanda",
  "Harshitha",
  "Chandana Rani",
  "Shailaja",
  "Suguna",
  "Radhika",
  "Rajya Lakshmi Latha",
  "Lahari Rani",
  "Mounika",
  "Sanjana",
  "Vasundhara",
  "Lalitha Priya",
  "Malathi Reddy",
  "Sowparnika",
  "Naga Jyothi Priya",
  "Nayana Reddy",
  "Tejaswini Sri",
  "Uma Devi",
  "Padmaja Kumari",
  "Jyostna",
  "Bhagya Lakshmi Kumari",
  "Ishika Rani",
  "Bhargavi Devi",
  "Supriya Rani",
  "Kanaka Durga",
  "Roja Naidu",
  "Anitha Priya",
  "Sahasra",
  "Eshwari Devi",
  "Rajitha",
  "Tulasi Reddy",
  "Kavya Priya",
  "Yamini Devi",
  "Chandrika Rani",
  "Rajya Lakshmi Rani",
  "Rakshita",
  "Kalindi",
  "Sri Vidya",
  "Sowmya",
  "Lakshmi",
  "Rajani",
  "Manasa Naidu",
  "Leela Kumari",
  "Srilatha",
  "Divya Rani",
  "Sreekala Naidu",
  "Shreya Priya",
  "Rakshita Naidu",
  "Sindhu Sri",
  "Gayatri",
  "Kavya Reddy",
  "Kumari",
  "Bhavani",
  "Gnana Prasuna",
  "Jaya",
  "Siri Rani",
  "Rajani Kanth",
  "Uma Sri",
  "Sameera Kumari",
  "Sindura",
  "Sowparnika Priya",
  "Prameela",
  "Vasanthi Latha",
  "Nagalakshmi",
  "Priyanka Latha",
  "Mythri Devi",
  "Sailaja",
  "Deepthi Priya",
  "Sanjeevani",
  "Nandini Naidu",
  "Jahnavi Rani",
  "Kausalya Kumari",
  "Kusuma Latha",
  "Renuka Naidu",
  "Ratnamala Kumari",
  "Supriya",
  "Krishnaveni",
  "Lavanya Bai",
  "Devika Bai",
  "Priyamvada Rani",
  "Shailaja Devi",
  "Sujatha",
  "Hema Priya",
  "Lakshmi Kumari",
  "Srija Rani",
  "Srija",
  "Devika Latha",
  "Sharada",
  "Rajya Lakshmi",
  "Vennela",
  "Swapna Rani",
  "Alekhya Sri",
  "Jyothsna Devi",
  "Sarada Kumari",
  "Vinitha Priya",
  "Sunanda Devi",
  "Radha",
  "Gnaneswari Latha",
  "Sulochana Devi",
  "Sravani",
  "Saroja Priya",
  "Jyothi Naidu",
  "Rakshita Devi",
  "Meghana Priya",
  "Ashwini",
  "Kanaka Durga Bai",
  "Sudha Kumari",
  "Sarayu Devi",
  "Nagalakshmi Latha",
  "Nirmala Priya",
  "Naga Sri",
  "Meena Kumari",
  "Krishnaveni Priya",
  "Manjula",
  "Ramanamma Latha",
  "Ishika Sri",
  "Shailaja Reddy",
  "Yashoda Devi",
  "Snigdha Devi",
  "Swapna",
  "Yasoda",
  "Nikita",
  "Jaya Naidu",
  "Eshwari Latha",
  "Meghali",
  "Ratnamala",
  "Vaishnavi",
  "Vani Kumari",
  "Hasini",
  "Nikita Priya",
  "Sudha",
  "Sujatha Reddy",
  "Shanmukha Priya",
  "Shreya",
  "Mamatha Priya",
  "Indu Priya",
  "Sahithi Sri",
  "Suhasini",
  "Sirisha Rani",
  "Praveena",
  "Tanuja Priya",
  "Neelambari Kumari",
  "Naveena",
  "Usha Bai",
  "Sudha Sri",
  "Nayana Kumari",
  "Spandana Bai",
  "Sitara",
  "Padma",
  "Pranitha Reddy",
  "Praveena Kumari",
  "Asha Priya",
  "Kamala Latha",
  "Sriya",
  "Suchitra Latha",
  "Vaani Sri",
  "Ramadevi",
  "Srilekha Sri",
  "Lasya",
  "Shalini Rani",
  "Madhavi Latha",
  "Meena",
  "Sahithi",
  "Saroja",
  "Naga Jyothi Rani",
  "Shravya Rani",
  "Ramya",
  "Kalpana Rani",
  "Sowbhagya",
  "Vamsi Priya",
  "Ramya Sri",
  "Parvathi Rani",
  "Tanuja",
  "Vimala Latha",
  "Revathi Priya",
  "Vaani Kumari",
  "Priyamvada Reddy",
  "Varalakshmi",
  "Preethi Reddy",
  "Gnaneswari",
  "Mrudula Priya",
  "Srija Devi",
  "Preethi",
  "Neelima Naidu",
  "Deepti Devi",
  "Vidya",
  "Soujanya Kumari",
  "Rukmini Bai",
  "Jahnavi Priya",
  "Veda Naidu",
  "Nithya Reddy",
  "Sreepriya Bai",
  "Mamatha",
  "Sunanda Bai",
  "Sahasra Kiran Reddy",
  "Trisha Rani",
  "Neelima",
  "Vaidehi Devi",
  "Aparna Reddy",
  "Roja Sri",
  "Rajitha Naidu",
  "Varalakshmi Kumari",
  "Vani",
  "Deepthi Reddy",
  "Nireeksha",
  "Haritha Devi",
  "Gowri Naidu",
  "Keerthi Priya",
  "Sita Naidu",
  "Swarna Devi",
  "Kanaka Durga Rani",
  "Nandini",
  "Anitha",
  "Sasikala Priya",
  "Mokshitha",
  "Savitri Priya",
  "Rajani Devi",
  "Mahalakshmi",
  "Sai Ramya",
  "Manasa",
  "Krupa Naidu",
  "Kamala",
  "Shravya",
  "Parvathi",
  "Sreepriya",
  "Rachana",
  "Asha",
  "Sahiti Rani",
  "Sowbhagya Bai",
  "Sri Lakshmi",
  "Ramanamma",
  "Yamini Priya",
  "Yashaswini",
  "Madhuri Latha",
  "Sitara Latha",
  "Meghali Priya",
  "Krupa",
  "Nikhita Sri",
  "Vijaya Lakshmi Priya",
  "Sandhya Sri",
];
