// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbwnwsaktoctqufipgab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFid253c2FrdG9jdHF1ZmlwZ2FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDk5MzksImV4cCI6MjA2OTk4NTkzOX0.5xrdhsGkVhVhFNkMVSyUkZe7hph0IMqlXQl9TdvvRM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // Required for OAuth redirects
    flowType: 'pkce', // More secure OAuth flow (Proof Key for Code Exchange)
  },
});
